### ISSUE TITLE
chrony.conf is not affected by osmap.yaml

### ISSUE THREAD

**Issue by lrodri29** [saltstack-formulas/chrony-formula#13]
When I add a desired IP address to the osmap.yaml, it does not add the server IP to /etc/chrony/chrony.conf

**Comment by aboe76** [comment]
@lrodri29 why are you adding an ip to osmap.yaml when you can override the defaults within pillar?

**Comment by lrodri29** [comment]
I was having no luck updating pillar/chrony.sls to:
```
chrony:
  ntpservers:
    - '0.amazon.pool.ntp.org'
    - '1.amazon.pool.ntp.org'
    - '2.amazon.pool.ntp.org'
    - '3.amazon.pool.ntp.org'
```

**Comment by aboe76** [comment]
@lrodri29 no problem,

I'm curious which states are active on your machine? chrony or chrony.config?

**Comment by lrodri29** [comment]
As of right now I have the unedited salt/chrony file which I refer to in my top.sls
In the pillar side of things, I have a chrony.sls which I posted above and on top.sls I have the following:
```
base:
  '*':
    - scalyr

  'endpoint*':
    - endpoint

  # Jenkins server for Django proofreader tests.
  'pr-jenkins*':
    - proofreader-jenkins

  # Jenkins server for Python scripts such as those in boss-tools.
  'jenkins*':
    - jenkins

  # Chrony NTP 
  'chrony*':
    - chrony
```

**Comment by aboe76** [comment]
@lrodri29 please try chrony.config as state instead of chrony

**Comment by lrodri29** [comment]
How so?

**Comment by aboe76** [comment]
@lrodri29 , the chrony state only installs and starts, the chrony.config state will do the install config and service.

**Comment by lrodri29** [comment]
So I just use -chrony.config in my top.sls file?

**Comment by aboe76** [comment]
@lrodri29 yes, if you look in the config.sls file you will see it includes chrony.sls ...

**Comment by lrodri29** [comment]
Should I include chrony.config in my pillar/top.sls or salt/top.sls

**Comment by lrodri29** [comment]
chron

**Comment by lrodri29** [comment]
Thank you!
