### ISSUE TITLE
server and pool options should be set separate.

### ISSUE THREAD

**Issue by aboe76** [saltstack-formulas/chrony-formula#27]
It would be nice to be able to set different options per server:

```
server ntp.time.nl iburst prefer
server ntp0.nl.net iburst
server ntp1.nl.net iburst
server ntp2.nl.net iburst
```
or
```
server ntp.time.nl iburst prefer
pool nl.pool.ntp.org iburst maxsources 3
```

**Comment by mdschmitt** [comment]
Is anyone watching this?  I'd like to see PR #37 merged if there aren't objections, though I did want to ask if it made sense to set the `options:` item as a list instead of a string value.  Makes more canonical sense to me personally, but I think it could go either way, really.
